export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const LOGIN_USER = "LOGIN_USER";
export const SIGNUP = "SIGNUP";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const RENDER_LOGIN =  "RENDER_LOGIN";
export const RENDER_SIGNUP =  "RENDER_SIGNUP";

export const DONOR_VAL_UPDATE = "DONOR_VAL_UPDATE";
export const DONOR_CREATED = "DONOR_CREATED";
export const DONORS_FETCH_SUCCESS = "DONORS_FETCH_SUCCESS";